Add debug flag
Co-authored-by: Cem Deniz Kabakci <cem.kabakci@springer.com>

diff --git a/.github/workflows/release-artifacts.yml b/.github/workflows/release-artifacts.yml
--- a/.github/workflows/release-artifacts.yml
+++ b/.github/workflows/release-artifacts.yml
@@ -89,7 +89,6 @@ jobs:
             CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
             CR_SKIP_EXISTING: "true"
 
-
       - name: Push charts to GHCR
         run: |
           shopt -s nullglob
@@ -97,5 +96,5 @@ jobs:
           ls -l .cr-release-packages/*
           for pkg in .cr-release-packages/*; do
             [ -z "${pkg:-}" ] && break
-            helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts" &&  echo "::warning:: helm push failed!" >> $GITHUB_OUTPUT
+            helm push --debug "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts" || echo "::warning:: helm push failed!" >> $GITHUB_OUTPUT
           done
